// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeApp.API.DbContexts;

#nullable disable

namespace RecipeApp.API.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20250204095307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeApp.API.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Quantity")
                        .HasMaxLength(50)
                        .HasColumnType("float");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black Pepper",
                            Quantity = 0.25,
                            RecipeId = 1,
                            Unit = "tablespoon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Black Pepper",
                            Quantity = 0.25,
                            RecipeId = 1,
                            Unit = "tablespoon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Meat",
                            Quantity = 1.0,
                            RecipeId = 2,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tomato",
                            Quantity = 2.0,
                            RecipeId = 2,
                            Unit = "tomatoes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Salt",
                            Quantity = 1.5,
                            RecipeId = 3,
                            Unit = "tablespoon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sugar",
                            Quantity = 5.0,
                            RecipeId = 3,
                            Unit = "tablespoon"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Olive Oil",
                            Quantity = 10.0,
                            RecipeId = 4,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tumeric",
                            Quantity = 1.0,
                            RecipeId = 4,
                            Unit = "tablespoon"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sugar",
                            Quantity = 5.0,
                            RecipeId = 5,
                            Unit = "tablespoon"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Baking Powder",
                            Quantity = 100.0,
                            RecipeId = 5,
                            Unit = "g"
                        });
                });

            modelBuilder.Entity("RecipeApp.API.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "You can add a pat of butter or some cheese to the center of each burger before cooking.\r\nYou can use almost any type of minced (ground) meat to make hamburgers, including pork, chicken, turkey, lamb, bison, venison, ostrich, or even a meat substitute such as Quorn. Some variations of hamburgers call for mixing different types of meat (e.g. ground beef and ground pork).\r\nOptional additions to burger patties prior to cooking include: black pepper, chili, Worcestershire Sauce, soy sauce, basil, oregano and parsley, minced garlic or garlic powder, onion flakes or diced onion, mustard, olive oil, cheese, butter, hot sauce, kosher salt, bread crumbs, and crushed crackers.\r\nDepending on the quality of your local beef, for example, you may wish to add some beef stock to improve the flavour. If you add any liquids, mix the ground beef well then squeeze out the extra juice when forming patties.",
                            Name = "Hamburger"
                        },
                        new
                        {
                            Id = 2,
                            Description = "You can add a pat of butter or some cheese to the center of each burger before cooking.\r\nYou can use almost any type of minced (ground) meat to make hamburgers, including pork, chicken, turkey, lamb, bison, venison, ostrich, or even a meat substitute such as Quorn. Some variations of hamburgers call for mixing different types of meat (e.g. ground beef and ground pork).\r\nOptional additions to burger patties prior to cooking include: black pepper, chili, Worcestershire Sauce, soy sauce, basil, oregano and parsley, minced garlic or garlic powder, onion flakes or diced onion, mustard, olive oil, cheese, butter, hot sauce, kosher salt, bread crumbs, and crushed crackers.\r\nDepending on the quality of your local beef, for example, you may wish to add some beef stock to improve the flavour. If you add any liquids, mix the ground beef well then squeeze out the extra juice when forming patties.",
                            Name = "Pilau"
                        },
                        new
                        {
                            Id = 3,
                            Description = "You can add a pat of butter or some cheese to the center of each burger before cooking.\r\nYou can use almost any type of minced (ground) meat to make hamburgers, including pork, chicken, turkey, lamb, bison, venison, ostrich, or even a meat substitute such as Quorn. Some variations of hamburgers call for mixing different types of meat (e.g. ground beef and ground pork).\r\nOptional additions to burger patties prior to cooking include: black pepper, chili, Worcestershire Sauce, soy sauce, basil, oregano and parsley, minced garlic or garlic powder, onion flakes or diced onion, mustard, olive oil, cheese, butter, hot sauce, kosher salt, bread crumbs, and crushed crackers.\r\nDepending on the quality of your local beef, for example, you may wish to add some beef stock to improve the flavour. If you add any liquids, mix the ground beef well then squeeze out the extra juice when forming patties.",
                            Name = "Meat Stew"
                        },
                        new
                        {
                            Id = 4,
                            Description = "You can add a pat of butter or some cheese to the center of each burger before cooking.\r\nYou can use almost any type of minced (ground) meat to make hamburgers, including pork, chicken, turkey, lamb, bison, venison, ostrich, or even a meat substitute such as Quorn. Some variations of hamburgers call for mixing different types of meat (e.g. ground beef and ground pork).\r\nOptional additions to burger patties prior to cooking include: black pepper, chili, Worcestershire Sauce, soy sauce, basil, oregano and parsley, minced garlic or garlic powder, onion flakes or diced onion, mustard, olive oil, cheese, butter, hot sauce, kosher salt, bread crumbs, and crushed crackers.\r\nDepending on the quality of your local beef, for example, you may wish to add some beef stock to improve the flavour. If you add any liquids, mix the ground beef well then squeeze out the extra juice when forming patties.",
                            Name = "Fruit Salad"
                        },
                        new
                        {
                            Id = 5,
                            Description = "You can add a pat of butter or some cheese to the center of each burger before cooking.\r\nYou can use almost any type of minced (ground) meat to make hamburgers, including pork, chicken, turkey, lamb, bison, venison, ostrich, or even a meat substitute such as Quorn. Some variations of hamburgers call for mixing different types of meat (e.g. ground beef and ground pork).\r\nOptional additions to burger patties prior to cooking include: black pepper, chili, Worcestershire Sauce, soy sauce, basil, oregano and parsley, minced garlic or garlic powder, onion flakes or diced onion, mustard, olive oil, cheese, butter, hot sauce, kosher salt, bread crumbs, and crushed crackers.\r\nDepending on the quality of your local beef, for example, you may wish to add some beef stock to improve the flavour. If you add any liquids, mix the ground beef well then squeeze out the extra juice when forming patties.",
                            Name = "Brownie Cake"
                        });
                });

            modelBuilder.Entity("RecipeApp.API.Entities.Ingredient", b =>
                {
                    b.HasOne("RecipeApp.API.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeApp.API.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
